# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0003_auto_20161012_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taichimove',
            options={'verbose_name': '動作', 'verbose_name_plural': '動作'},
        ),
        migrations.AlterModelOptions(
            name='taichiset',
            options={'verbose_name': '招式', 'verbose_name_plural': '招式'},
        ),
        migrations.AlterModelOptions(
            name='taichistyle',
            options={'verbose_name': '線路', 'verbose_name_plural': '線路'},
        ),
        migrations.AddField(
            model_name='taichistyle',
            name='code',
            field=models.CharField(default='x', max_length=6, verbose_name='編碼'),
        ),
    ]
