# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0009_auto_20161013_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taichimove',
            name='taichiset',
        ),
    ]
