# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0010_remove_taichimove_taichiset'),
    ]

    operations = [
        migrations.AddField(
            model_name='taichimove',
            name='pagenum',
            field=models.IntegerField(default=130, verbose_name='第幾頁'),
        ),
    ]
