# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0011_taichimove_pagenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taichimove',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='動作要求'),
        ),
    ]
