# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0013_auto_20161014_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taichimove',
            name='setnum',
            field=models.IntegerField(default=1, verbose_name='第幾式'),
        ),
        migrations.AlterField(
            model_name='taichimove',
            name='stylenum',
            field=models.IntegerField(default=19, verbose_name='幾式'),
        ),
    ]
