# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0004_auto_20161012_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taichimove',
            options={'verbose_name': '(3)動作', 'verbose_name_plural': '(3)動作'},
        ),
        migrations.AlterModelOptions(
            name='taichiset',
            options={'verbose_name': '(2)招式', 'verbose_name_plural': '(2)招式'},
        ),
        migrations.AlterModelOptions(
            name='taichistyle',
            options={'verbose_name': '線路', 'verbose_name_plural': '(1)線路'},
        ),
        migrations.RemoveField(
            model_name='taichiset',
            name='num',
        ),
        migrations.AddField(
            model_name='taichimove',
            name='mynote',
            field=models.CharField(default='.', max_length=200, verbose_name='我的筆記'),
        ),
    ]
