# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0006_auto_20161012_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='taichimove',
            name='mnemonic',
            field=models.CharField(default='.', max_length=20, verbose_name='助憶'),
        ),
        migrations.AlterField(
            model_name='taichimove',
            name='description',
            field=models.CharField(max_length=200, verbose_name='動作要求'),
        ),
        migrations.AlterField(
            model_name='taichimove',
            name='title',
            field=models.CharField(max_length=200, verbose_name='動作口訣'),
        ),
        migrations.AlterField(
            model_name='taichiset',
            name='description',
            field=models.CharField(max_length=200, verbose_name='招式說明'),
        ),
        migrations.AlterField(
            model_name='taichiset',
            name='taichistyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itaiching.TaichiStyle', verbose_name='線路名稱'),
        ),
        migrations.AlterField(
            model_name='taichiset',
            name='title',
            field=models.CharField(max_length=200, verbose_name='招式名稱'),
        ),
    ]
