# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0007_auto_20161012_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='taichimove',
            name='stylenum',
            field=models.IntegerField(default=0, verbose_name='幾式'),
        ),
    ]
