# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaichiMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaichiSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaichiStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='taichiset',
            name='taichistyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itaiching.TaichiStyle'),
        ),
        migrations.AddField(
            model_name='taichimove',
            name='taichiset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itaiching.TaichiSet'),
        ),
    ]
