# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taichimove',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taichiset',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
