# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itaiching', '0008_taichimove_stylenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taichimove',
            old_name='num',
            new_name='movenum',
        ),
        migrations.AddField(
            model_name='taichimove',
            name='setnum',
            field=models.IntegerField(default=0, verbose_name='第幾式'),
        ),
    ]
